failure_phrases = [
	"Wrong.",
	"You have failed.",
	"Incorrect.",
	"no",
	"You utter fool",
	"Fool..,",
	"Error!",
	"ERROR:",
	"You have erred.",
	"Imagine writing code that makes this error:",
	"Do you are have dumb?",
	"what!",
	"Bad at computer!",
	"Bad at computer. Bad at computer!",
	"oh no",
	"Ooerror",
	"the ooerror is ooer",
	"error ooer-ror oo-errorwhat are you doing",
	"latery Eror! Er Erry Err! later!ЕГГОГ",
	"EGGOG",
	"An error occuAn error oAn error occurred.",
	"Plearror occuAn error oAn ain later",
]
