target-version = "py313"
src = ["."]
line-length = 80
indent-width = 4

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[format]
indent-style = "tab"
quote-style = "double"

[lint]
extend-select = [
    "I",    # isort: https://docs.astral.sh/ruff/rules/#isort-i
    "UP",   # pyupgrade: https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "ANN",  # annotations: https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
]
ignore = [
    "ANN204",  # return type annotation for special method `__init__`
]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[lint.isort]
case-sensitive = true
lines-after-imports = 2

[lint.flake8-annotations]
suppress-dummy-args = true
